version: 2
jobs:
  markdown-spell-check:
    docker:
    - image: shidaqiu/servicemesher-trans-circleci:1.0
    working_directory: ~/site
    steps:
    - checkout
    - run:
        name: Running markdown spell check
        command: scripts/mdspell-check.sh
  markdown-style-check:
    docker:
    - image: shidaqiu/servicemesher-trans-circleci:1.0
    working_directory: ~/site
    steps:
    - checkout
    - run:
        name: Running markdown style check
        command: scripts/mdl-check.sh
workflows:
  version: 2
  workflow:
    jobs:
    - markdown-spell-check
    - markdown-style-check